### ISSUE TITLE
question about tutorial_NMNIST.py

### ISSUE THREAD

**Issue by shirleyatgithub** [jubueche/SPAA#8]
dear author,
thanks for sharing the code. I run into an problem with tutorial_NMNIST.py which outputs
FileNotFoundError: [Errno 2] No such file or directory: 'data\\N-MNIST\\test_Files.zip' error.
I wonder where to find the data, the raw dataset from downloaded N-MNIST?
Looking forward to your reply

**Comment by jubueche** [comment]
That's weird. It should download the data automatically here: https://github.com/jubueche/SPAA/blob/b1f293582005ff22f54e177e36ce715a675677d5/dataloader_NMNIST.py#L35

Can you maybe break there and check why this is not downloading? Maybe there is a pathing issue.

**Comment by shirleyatgithub** [comment]
Thank you for the quick reply. I checked the code and found they are on dropbox which is not accessible for me. I wonder if there is any possibility that I can get access to the dataset from another link, such as github or onedrive?



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Julian ***@***.***> |
| Date | 03/10/2023 15:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jubueche/SPAA] question about tutorial_NMNIST.py (Issue #8) |

That's weird. It should download the data automatically here: https://github.com/jubueche/SPAA/blob/b1f293582005ff22f54e177e36ce715a675677d5/dataloader_NMNIST.py#L35

Can you maybe break there and check why this is not downloading? Maybe there is a pathing issue.

**Comment by jubueche** [comment]
You can download it from here: https://www.garrickorchard.com/datasets/n-mnist
I am closing this now :)

**Comment by shirleyatgithub** [comment]
Thank you!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Julian ***@***.***> |
| Date | 03/10/2023 15:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jubueche/SPAA] question about tutorial_NMNIST.py (Issue #8) |

You can download it from here: https://www.garrickorchard.com/datasets/n-mnist
I am closing this now :)

**Comment by shirleyatgithub** [comment]
Dear Julian,
I am Shasha Guo from NUDT, China. I read your paper "Exploring Adversarial Attack in Spiking Neural Networks with Spike-Compatible Gradient" and am very interested in it. And thank you for sharring the code. I tried the universal patch attack on NMNIST but the success rate is very low at around 0.2, I wonder if it's right. And there's another question is that you have mentioned adversarial training in the paper, I wonder if you have include it in the project?
Thanks for your attention.
Best wishes,
Shasha Guo













At 2023-03-10 15:55:07, "GUO SHASHA" ***@***.***> wrote:

Thank you!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Julian ***@***.***> |
| Date | 03/10/2023 15:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jubueche/SPAA] question about tutorial_NMNIST.py (Issue #8) |

You can download it from here: https://www.garrickorchard.com/datasets/n-mnist
I am closing this now :)

**Comment by jubueche** [comment]
Hi,

I haven’t run the patch code in a while so it’s likely there is still an issue. Could you write to me at jub (at) zurich.ibm.com ?
________________________________
From: shirleyatgithub ***@***.***>
Sent: Wednesday, July 19, 2023 5:30:27 AM
To: jubueche/SPAA ***@***.***>
Cc: Julian Buechel1 ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [jubueche/SPAA] question about tutorial_NMNIST.py (Issue #8)

Dear Julian, I am Shasha Guo from NUDT, China. I read your paper "Exploring Adversarial Attack in Spiking Neural Networks with Spike-Compatible Gradient" and am very interested in it. And thank you for sharring the code. I tried the
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2i-qihQ34BPxsIZXtI9rrdxmJFzoE6CmZlYYzwZ1-tGjjbonxaB8hvsSXGQhGSDp8mMkNfA0p29gLsbZRcZmUEYaBPdi5A$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Dear Julian,
I am Shasha Guo from NUDT, China. I read your paper "Exploring Adversarial Attack in Spiking Neural Networks with Spike-Compatible Gradient" and am very interested in it. And thank you for sharring the code. I tried the universal patch attack on NMNIST but the success rate is very low at around 0.2, I wonder if it's right. And there's another question is that you have mentioned adversarial training in the paper, I wonder if you have include it in the project?
Thanks for your attention.
Best wishes,
Shasha Guo













At 2023-03-10 15:55:07, "GUO SHASHA" ***@***.***> wrote:

Thank you!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Julian ***@***.***> |
| Date | 03/10/2023 15:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jubueche/SPAA] question about tutorial_NMNIST.py (Issue #8) |

You can download it from here: https://www.garrickorchard.com/datasets/n-mnist<https://www.garrickorchard.com/datasets/n-mnist>
I am closing this now :)
