### ISSUE TITLE
about tutorial_NMNIST.py

### ISSUE THREAD

**Issue by shirleyatgithub** [jubueche/SPAA#9]
Dear author,
I encounter another problem, wondering if you know about it. I have installed sinabs from pip following the readme.md.
Traceback (most recent call last):
File "tutorial_NMNIST.py", line 3, in
from networks import train_ann_mnist, get_summed_network
File "SPAA-main\networks.py", line 3, in
from sinabs.layers.iaf_bptt import SpikingLayer
ModuleNotFoundError: No module named 'sinabs.layers.iaf_bptt'

**Comment by jubueche** [comment]
Try `pip install sinabs==0.2.1`

**Comment by shirleyatgithub** [comment]
I download sinabs==0.2.1, and it pops out "Failed to import sinabs". but in python I can import sinabs. really wierd.
![image](https://user-images.githubusercontent.com/56689341/224548949-db29d686-f275-485e-88c5-a08cf6313612.png)

**Comment by jubueche** [comment]
That’s weird. It works for me on linux. Maybe this is a problem associated to windows. I am not sure if sinabs works on windows.

**Comment by shirleyatgithub** [comment]
thx, then I'll try it on linux
